/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: b49b5e54cfb13cc9b34de3d3e9f66d13)
interface __BaseEnv_Env {
	ASSETS: Fetcher;
	RESEND_API_KEY: string;
	RESEND_FROM_EMAIL: string;
	RESEND_FROM_NAME: string;
	CONTACT_EMAIL: string;
	TURNSTILE_SITE_KEY: string;
	TURNSTILE_SECRET_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./server/app");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "RESEND_API_KEY" | "RESEND_FROM_EMAIL" | "RESEND_FROM_NAME" | "CONTACT_EMAIL" | "TURNSTILE_SITE_KEY" | "TURNSTILE_SECRET_KEY">> {}
}
